blank_issues_enabled: false
contact_links:
  - name: PaperMC Discord
    url: http://discord.gg/papermc
    about: If you are having issues with timings or have other minor issues, come ask us on our Discord server!
